# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de4626f4e401b58c6fe354d9bc85ce28b57b40ac736ca72955e75cc5eabec54ef927d17120c7b44d0546f279f2dd7cc0010fcdd8f69acf973421d00bb4767e08

test:
  secret_key_base: d6a847a938ebca50f01645a4581bd7b9dc831824435724138a1c162512b352c9617214afe043207a9ce7f0bb648b9c9a674d1fbc123b239d6d296c399abbe43c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
